### PR TITLE
fix crash on unwrapping optionals when migration fails

### PR DESCRIPTION
**Pull request by max-potapov**

### CODE REVIEW

**Comment by pepibumur** [comment]
:clap: thanks @max-potapov

**Comment by pepibumur** [comment]
@max-potapov  could you run the ci.sh script on the root library folder and check if it passes?

**Comment by max-potapov** [comment]
@pepibumur Sure
```
** TEST SUCCEEDED: 110 passed, 0 failed, 0 errored, 110 total ** (27261 ms)

ci.sh: line 14: pod: command not found
ERROR: Cannot find schemes. Please consider creating shared schemes in Xcode.
```

**Comment by pepibumur** [comment]
:clap: pa lante!

**Pull request merged**
