### PR TITLE
Fixed for Swift 1.2

### PR DESCRIPTION
**Pull request by dchavezlive**
"Forced failable conversion now uses the as! operator."

"Immutable (let) properties in struct and class initializers have been revised to standardize on a general “lets are singly initialized but never reassigned or mutated” model."

### CODE REVIEW

**Comment by pepibumur** [comment]
@dchavezlive isn't Travis working due to the update of Swift?
Great Job BTW :stuck_out_tongue:

**Comment by dchavezlive** [comment]
Travis is probably failing because it isn't using Swift 1.2

**Comment by pepibumur** [comment]
Merged, thanks @dchavezlive

**Comment by pepibumur** [comment]
@dchavezlive is the Swift version 1.2 official? or just a version included in a XCode beta?

**Comment by dchavezlive** [comment]
Sorry, I assumed you knew and I guess that should've been mentioned. Its included in the Xcode beta so this should probably be merged into a branch for now.

**Comment by pepibumur** [comment]
Yep! I didn't stop thinking about it. I've created a branch for that purpose @dchavezlive and left develop in its current state that supports the current version of Swift. Here is the branch: https://github.com/SugarRecord/SugarRecord/tree/swift12Support

**Comment by dchavezlive** [comment]
That should be good enough for the people that will start working with the beta. I believe someone raised an issue about it already.

**Comment by pepibumur** [comment]
Yes there's an issue opened, feel free to close it if it's covered with this PR.

**Pull request merged**
