### PR TITLE
Fixed RestKit example crashing when adding entry

### PR DESCRIPTION
**Pull request by dchavezlive**
App no longer crashes when using the RestKit example and adding a new row

### CODE REVIEW

**Comment by pepibumur** [comment]
:clap: amazing job here also @dchavezlive

**Comment by dchavezlive** [comment]
This fixes a bug that was present even before the Swift 1.2 support. However, this fix does have 1.2 code in it. (using the as! operator)

**Comment by pepibumur** [comment]
mmm, we can add it to the branch of Swift 1.2 which I think will be released soon.

**Comment by dchavezlive** [comment]
Well, it seems that the develop branch still has the 1.2 changes in there as that's the branch i pulled to add these fixes.

**Pull request closed without merging**
